/*
 * *** DO NOT EDIT THIS FILE ***
 *
 * This file contains external declarations for UIParameter objects
 * generated by the "mobu" utility.  If you need to add a parameter,
 * you should go to mobu and add it to the parameters.xml file and
 * regenerate the Classes files.  Failure to do so will result in
 * changes being lost the next time mobu generated files are exported.
 *
 */

#pragma once

/*** GENERATED ***/

extern class UIParameter* UIParameterActiveSetup;
extern class UIParameter* UIParameterDefaultPreset;
extern class UIParameter* UIParameterActiveOverlay;
extern class UIParameter* UIParameterFadeFrames;
extern class UIParameter* UIParameterMaxSyncDrift;
extern class UIParameter* UIParameterDriftCheckPoint;
extern class UIParameter* UIParameterLongPress;
extern class UIParameter* UIParameterSpreadRange;
extern class UIParameter* UIParameterTraceLevel;
extern class UIParameter* UIParameterAutoFeedbackReduction;
extern class UIParameter* UIParameterIsolateOverdubs;
extern class UIParameter* UIParameterMonitorAudio;
extern class UIParameter* UIParameterSaveLayers;
extern class UIParameter* UIParameterQuickSave;
extern class UIParameter* UIParameterIntegerWaveFile;
extern class UIParameter* UIParameterGroupFocusLock;
extern class UIParameter* UIParameterTrackCount;
extern class UIParameter* UIParameterGroupCount;
extern class UIParameter* UIParameterMaxLoops;
extern class UIParameter* UIParameterInputLatency;
extern class UIParameter* UIParameterOutputLatency;
extern class UIParameter* UIParameterNoiseFloor;
extern class UIParameter* UIParameterMidiRecordMode;
extern class UIParameter* UIParameterSubcycles;
extern class UIParameter* UIParameterMultiplyMode;
extern class UIParameter* UIParameterShuffleMode;
extern class UIParameter* UIParameterAltFeedbackEnable;
extern class UIParameter* UIParameterEmptyLoopAction;
extern class UIParameter* UIParameterEmptyTrackAction;
extern class UIParameter* UIParameterTrackLeaveAction;
extern class UIParameter* UIParameterLoopCount;
extern class UIParameter* UIParameterMuteMode;
extern class UIParameter* UIParameterMuteCancel;
extern class UIParameter* UIParameterOverdubQuantized;
extern class UIParameter* UIParameterQuantize;
extern class UIParameter* UIParameterBounceQuantize;
extern class UIParameter* UIParameterRecordResetsFeedback;
extern class UIParameter* UIParameterSpeedRecord;
extern class UIParameter* UIParameterRoundingOverdub;
extern class UIParameter* UIParameterSwitchLocation;
extern class UIParameter* UIParameterReturnLocation;
extern class UIParameter* UIParameterSwitchDuration;
extern class UIParameter* UIParameterSwitchQuantize;
extern class UIParameter* UIParameterTimeCopyMode;
extern class UIParameter* UIParameterSoundCopyMode;
extern class UIParameter* UIParameterRecordThreshold;
extern class UIParameter* UIParameterSwitchVelocity;
extern class UIParameter* UIParameterMaxUndo;
extern class UIParameter* UIParameterMaxRedo;
extern class UIParameter* UIParameterNoFeedbackUndo;
extern class UIParameter* UIParameterNoLayerFlattening;
extern class UIParameter* UIParameterSpeedShiftRestart;
extern class UIParameter* UIParameterPitchShiftRestart;
extern class UIParameter* UIParameterSpeedStepRange;
extern class UIParameter* UIParameterSpeedBendRange;
extern class UIParameter* UIParameterPitchStepRange;
extern class UIParameter* UIParameterPitchBendRange;
extern class UIParameter* UIParameterTimeStretchRange;
extern class UIParameter* UIParameterSlipMode;
extern class UIParameter* UIParameterSlipTime;
extern class UIParameter* UIParameterAutoRecordTempo;
extern class UIParameter* UIParameterAutoRecordBars;
extern class UIParameter* UIParameterRecordTransfer;
extern class UIParameter* UIParameterOverdubTransfer;
extern class UIParameter* UIParameterReverseTransfer;
extern class UIParameter* UIParameterSpeedTransfer;
extern class UIParameter* UIParameterPitchTransfer;
extern class UIParameter* UIParameterWindowSlideUnit;
extern class UIParameter* UIParameterWindowEdgeUnit;
extern class UIParameter* UIParameterWindowSlideAmount;
extern class UIParameter* UIParameterWindowEdgeAmount;
extern class UIParameter* UIParameterDefaultSyncSource;
extern class UIParameter* UIParameterDefaultTrackSyncUnit;
extern class UIParameter* UIParameterSlaveSyncUnit;
extern class UIParameter* UIParameterManualStart;
extern class UIParameter* UIParameterMinTempo;
extern class UIParameter* UIParameterMaxTempo;
extern class UIParameter* UIParameterBeatsPerBar;
extern class UIParameter* UIParameterMuteSyncMode;
extern class UIParameter* UIParameterResizeSyncAdjust;
extern class UIParameter* UIParameterSpeedSyncAdjust;
extern class UIParameter* UIParameterRealignTime;
extern class UIParameter* UIParameterOutRealign;
extern class UIParameter* UIParameterActiveTrack;
extern class UIParameter* UIParameterTrackName;
extern class UIParameter* UIParameterStartingPreset;
extern class UIParameter* UIParameterActivePreset;
extern class UIParameter* UIParameterFocus;
extern class UIParameter* UIParameterGroup;
extern class UIParameter* UIParameterMono;
extern class UIParameter* UIParameterFeedback;
extern class UIParameter* UIParameterAltFeedback;
extern class UIParameter* UIParameterInput;
extern class UIParameter* UIParameterOutput;
extern class UIParameter* UIParameterPan;
extern class UIParameter* UIParameterSyncSource;
extern class UIParameter* UIParameterTrackSyncUnit;
extern class UIParameter* UIParameterAudioInputPort;
extern class UIParameter* UIParameterAudioOutputPort;
extern class UIParameter* UIParameterPluginInputPort;
extern class UIParameter* UIParameterPluginOutputPort;
extern class UIParameter* UIParameterSpeedOctave;
extern class UIParameter* UIParameterSpeedStep;
extern class UIParameter* UIParameterSpeedBend;
extern class UIParameter* UIParameterPitchOctave;
extern class UIParameter* UIParameterPitchStep;
extern class UIParameter* UIParameterPitchBend;
extern class UIParameter* UIParameterTimeStretch;
