baseURL = "/"
title = "Möbius 3"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Möbius 3" # title for frontpage, may include image
copyright = "Jeffrey Larson"
description = 'The Möbius Programmable Looper <br />Rises from the ashes'
#startbuttonText = "Download"
#startbuttonLink = "/downloads"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/downloads/'
title = "Downloads"

[[params.menu.main]]
url = '/documentation/'
title = "Documentation"

[[params.menu.main]]
url = 'http://www.mobiuslooper.com/forum'
title = "Community"

#[[params.menu.main]]
#url = '/subscribe'
#title = "Subscribe"

[[params.menu.main]]
url = 'fileshare/public.php'
title = "Library"

[[params.menu.main]]
url = '/about/'
title = "About"

[params.one]
enable = true
title = 'Welcome to the new Mobius'
body = '''
Mobius 3 is available as an early beta release for 64-bit Windows and Mac computers.
It runs as both a standalone application and as a VST3 and AudioUnit plugin.
While most of the functionality of the original Mobius has been preserved, it has been extensively redesigned and will not be stable for awhile.
You are welcome to try it and report any problems you may encounter, but it is not recommended for serious use.
If you are new to Mobius, this may not be the best time to become involved. If you are an experienced user that would like to test the new version, please create a forum account.
The forum can be accessed from the **Community** item in the main menu.  There is also an active [Mobius Group](https://www.facebook.com/groups/mobiuscentral) on Facebook.
'''

