#baseURL = 'https://example.org/'
#languageCode = 'en-us'
#title = 'My New Hugo Site'
#theme = 'spectral'
#copyright = 'Circular Labs'

baseURL = "/"
title = "Möbius 3"
languageCode = "en-us"
defaultContentLanguage = "en"
paginate = "7"
theme = "spectral"

[params]
fancyTitle = "Möbius 3" # title for frontpage, may include image
copyright = "Jeffrey Larson"
description = 'The Möbius Programmable Looper<br />Rises from the ashes'
startbuttonText = "Download"
startbuttonLink = "/downloads"
body_is_markdown = true

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/downloads/'
title = "Downloads"

[[params.menu.main]]
url = '/documentation/'
title = "Documentation"

[[params.menu.main]]
url = 'http://www.circularlabs.com/forum'
title = "Community"

[[params.menu.main]]
url = '/subscribe'
title = "Subscribe"

[[params.menu.main]]
url = '/about/'
title = "About"

[params.one]
enable = true
title = 'Welcome to the new Mobius'
body = '''
Mobius 3 is available as a beta release and is not intended for general use.  If you are familiar with old Mobius feel free to download it, try it out, and send problem reports.  But it is not in a state where it should be used for any serious performance, and we are not ready to support new users learning it for the first time.  A support forum is still evolving, the best place for discussion is the [Mobius Group](https://www.facebook.com/groups/mobiuscentral) on Facebook.
'''

