name = "Spectral"
license = "CC-BY 3.0"
licenselink = "https://github.com/sbruder/spectral/blob/master/LICENSE.md"
description = "Port of the HTML5UP Spectral Theme (https://html5up.net/spectral)"
homepage = "https://github.com/sbruder/spectral"
tags = ["company", "portfolio", "blog"]
features = ["blog", "responsive", "multilingual"]

demosite = "https://sbruder.github.io/spectral/"

[author]
  name = "Simon Bruder"

[original]
  name = "HTML5UP Spectral"
  homepage = "https://html5up.net/spectral"
